name: update-flake-lock
on:
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        uses: xgroleau/update-flake-lock@5a7892d53493794e73a3f5a30e05f7471ce5019f
        with:
          nix-options: --debug --log-format raw
