name: update-flake-lock
on:
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        uses: xgroleau/update-flake-lock@e874431a0685a3118d903568b7d9d2d7fbb3c3ce
        with:
          nix-options: --debug --log-format raw
